on:
  push:
    tags:
    - v*

jobs:
  build_job:
    name: gradle run build
    runs-on: ubuntu-latest
    
    steps:
    - name: 현재 브랜치로 checkout
      uses: actions/checkout@v3
    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'
    - name: gradle 빌드 시작
      run: ./gradlew build --parallel
    - name: jar 파일 생성
      run: ./gradlew jar
    - name: 파일명 변경
      run: mv ./build/libs/*.jar deploy-${{ github.sha }}.jar
    - name: 파일 압축
      run: zip -r deploy-${{ github.sha }}.zip deploy-${{ github.sha }}.jar
    - run: ls -al