on:
  push:
    branches:
      - master
    tags:
      - v*-prod

env:
  IMAGE_TAG: netty-${{ github.sha }}

jobs:
  build-job:
    if: ${{ github.ref_type == 'tag' || startsWith(github.event.head_commit.message, 'deploy:') }}
    runs-on: ubuntu-latest
    steps:
      - name: 현재 브랜치로 checkout
        uses: actions/checkout@v3
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: gradle 빌드
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: artifact 업로드
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            build/libs/*.jar
            Dockerfile
  deploy-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - name: artifact 다운로드
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: AWS 인증 정보 확인
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2
      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: 도커 이미지 빌드 & 푸시
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: jys-hub
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}