on:
  push:
    branches:
      - master

jobs:
  build_job:
    if: ${{ startsWith(github.event.head_commit.message, 'deploy:') }}
    runs-on: ubuntu-latest
    steps:
    - name: AWS 인증 정보 확인
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2
    - name: 현재 브랜치로 checkout
      uses: actions/checkout@v3
    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'
    - name: gradle 빌드 시작
      run: ./gradlew build --parallel
    - name: jar 파일 생성
      run: ./gradlew jar
    - name: 도커파일 빌드
      env:
        HASH: ${{ github.sha }}
      run: docker build -t ${{ env.HASH }} .
    - run: docker images