on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build_job:
    name: gradle run build
    runs-on: ubuntu-latest
    
    steps:
    - name: 현재 브랜치로 checkout
      uses: actions/checkout@v3
    - name: JDK 17 설정
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'gradle'
    - name: gradle 빌드 시작
      run: ./gradlew build --parallel